"""Data contract for the evidence-grounded improvement pipeline.

These Pydantic models are the shared vocabulary every stage speaks (design doc
sections 6.1-6.4). They encode the reliability-first decisions:
  - proposals must cite inspectable Evidence,
  - acceptance criteria declare HOW they're verified (mode + method),
  - benefit/risk/effort/confidence + an explicit proceed/abstain/needs_human
    decision (LLM scores are inputs; a deterministic policy gate decides),
  - a frozen+hashed proposal so approved intent can't silently drift.

Models are ordered so dependencies come before the models that use them (no
forward references needed).
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, model_validator

# --- primitives -----------------------------------------------------------------


class Evidence(BaseModel):
    # every claim must point at something inspectable.
    source_type: Literal["trajectory", "test", "benchmark", "code", "log"]
    reference: str  # e.g. "ours/agent/query.py:52", "traces/run1.jsonl#span3"
    observation: str


class Finding(BaseModel):
    # a verdict's structured note about a change unit (design doc section 8).
    severity: Literal["info", "minor", "major", "blocker"]
    location: str
    description: str
    evidence: str = ""
    required_fix: str = ""
    related_criterion: str = ""  # AcceptanceCriterion.id


class Metric(BaseModel):
    # a measurable target for metric-based acceptance.
    name: str
    direction: Literal["increase", "decrease"]
    min_delta: float = 0.0  # primary: required improvement; guardrail: allowed regression


class ContractClause(BaseModel):
    """One traceable requirement in the shared Writer/Reviewer task contract."""

    id: str
    description: str


class ImprovementTask(BaseModel):
    # One frozen implementation contract in the proposal's DAG. The Writer
    # implements it and the Reviewer audits the same clauses; neither side gets
    # to redefine success during execution.
    id: str
    # Name of the one selected Candidate this Loop's one Task implements.
    candidate: str = ""
    description: str
    rationale: str = ""
    capability_change: str = ""
    required_behaviors: list[ContractClause] = Field(default_factory=list)
    implementation_constraints: list[ContractClause] = Field(default_factory=list)
    invariants: list[ContractClause] = Field(default_factory=list)
    prohibited_shortcuts: list[ContractClause] = Field(default_factory=list)
    affected_components: list[str] = Field(default_factory=list)
    reviewer_focus: list[str] = Field(default_factory=list)
    # Named safety properties that must be covered by assigned executable
    # acceptance criteria. Keep this small and extensible instead of embedding
    # tool-specific checks in the Reviewer prompt.
    required_safety_properties: list[Literal["path_confinement"]] = Field(
        default_factory=list
    )
    dependencies: list[str] = Field(default_factory=list)
    acceptance_criteria_ids: list[str] = Field(default_factory=list)


class AcceptanceCriterion(BaseModel):
    # A traceable, executable delivery/commit condition for the TARGET AGENT SYSTEM
    # change itself—not a benchmark of code generated by that target agent.
    id: str
    description: str
    mode: Literal["red_green", "invariant", "metric_improvement", "non_regression", "manual"]
    check_type: Literal["unit", "integration", "smoke"] = "unit"
    verification: Literal["command", "review", "manual"] = "command"
    command: str = ""
    expected_exit_code: int = 0
    required_output_contains: list[str] = Field(default_factory=list)
    forbidden_output_contains: list[str] = Field(default_factory=list)
    verified_safety_properties: list[Literal["path_confinement"]] = Field(
        default_factory=list
    )
    # rigor of the functional test the Test Agent generates:
    #   full    -> core/framework: happy path + edges + error handling + invariants
    #   focused -> important logic: unit test asserting key values + intermediates
    #   basic   -> simple: one unit test on the main behavior
    # Ignored for metric modes (verified via the runner's external benchmark hook)
    # and manual mode (human-reviewed); the Test Agent does not auto-generate those.
    test_level: Literal["full", "focused", "basic"] = "focused"
    # Compatibility/advisory flag. Deterministic delivery only hard-enforces
    # delivery_run plus criteria carrying an explicit safety property.
    required: bool = False


class EvaluationPlan(BaseModel):
    # the frozen evaluation design: what to run + the metric gates.
    primary_metric: Metric | None = None
    guardrail_metrics: list[Metric] = Field(default_factory=list)
    scenarios: list[str] = Field(default_factory=list)  # test-agent turns these into runs
    run_count: int = 1  # repeat runs for nondeterministic behavior


class ExecutableCondition(BaseModel):
    """One typed runtime condition materialized by the trusted Runner."""

    name: str = Field(
        min_length=1,
        max_length=64,
        pattern=r"^[A-Za-z0-9][A-Za-z0-9._+-]*$",
    )
    state: Literal["available", "unavailable"]


class DeliveryScenario(BaseModel):
    """Frozen end-to-end prompt executed against the improved target agent."""

    id: str
    prompt: str
    # Safe argv form. Supported placeholders: {prompt} and {workspace}.
    command: list[str]
    fixture_files: dict[str, str] = Field(default_factory=dict)
    expected_behaviors: list[str] = Field(default_factory=list)
    forbidden_behaviors: list[str] = Field(default_factory=list)
    # The Orchestrator declares bounded runtime conditions; the Runner validates
    # and materializes them without accepting arbitrary env values or setup code.
    executable_conditions: list[ExecutableCondition] = Field(
        default_factory=list,
        max_length=8,
    )
    # Required when acceptance depends on internal tool use, ordering, or another
    # process fact that stdout and final artifacts cannot independently establish.
    requires_trajectory: bool = False


class ReviewResult(BaseModel):
    # the Reviewer's verdict on a change unit.
    verdict: Literal["accept", "revise", "escalate"]
    findings: list[Finding] = Field(default_factory=list)
    summary: str = ""


class ExecutionBlocker(BaseModel):
    # raised when a task can't converge within bounded Writer-Reviewer rounds.
    task_id: str
    review_rounds: int
    unresolved_findings: list[Finding] = Field(default_factory=list)
    attempted_fixes: list[str] = Field(default_factory=list)
    affected_tasks: list[str] = Field(default_factory=list)
    recommendation: Literal["abstain_task", "amend_plan", "request_human", "abort_proposal"]


class DiagnosticFinding(BaseModel):
    """Evidence-backed distinction between a symptom and an underlying capability gap."""

    symptom: str
    root_cause: str
    capability_gap: str
    evidence_refs: list[str] = Field(default_factory=list)
    uncertainty: str = ""


class InterventionCandidate(BaseModel):
    """One alternative considered before the Orchestrator selects a plan."""

    name: str
    level: Literal["prompt", "workflow", "tool", "module", "architecture"]
    mechanism: str
    expected_capability_delta: str
    evidence_strength: int = 1
    benefit: int = 1
    risk: int = 1
    effort: int = 1
    dependencies: list[str] = Field(default_factory=list)
    conflicts_with: list[str] = Field(default_factory=list)
    rejected_reason: str = ""


class ImprovementBatchBudget(BaseModel):
    """Compatibility metadata for the one-Candidate/one-Task Loop budget."""

    max_candidates: int = Field(default=1, ge=1, le=3)
    max_tasks: int = Field(default=1, ge=1, le=6)
    max_total_effort: int = Field(default=6, ge=1, le=6)
    selected_total_effort: int = Field(default=0, ge=0, le=6)


class OrchestratorAnalysis(BaseModel):
    """Diagnosis plus selection of one Candidate for the next Loop."""

    findings: list[DiagnosticFinding] = Field(default_factory=list)
    candidates: list[InterventionCandidate] = Field(default_factory=list)
    selected_candidates: list[str] = Field(default_factory=list)
    batch_budget: ImprovementBatchBudget = Field(default_factory=ImprovementBatchBudget)
    packing_reason: str = ""
    compatibility_notes: list[str] = Field(default_factory=list)
    selection_reason: str = ""
    causal_mechanism: str = ""
    expected_capability_delta: str = ""

    @model_validator(mode="before")
    @classmethod
    def migrate_singular_selection(cls, value):
        """Read older proposal JSON that used ``selected_candidate``."""
        if isinstance(value, dict):
            data = dict(value)
            if not data.get("selected_candidates") and data.get("selected_candidate"):
                data["selected_candidates"] = [str(data["selected_candidate"])]
            return data
        return value

    @property
    def selected_candidate(self) -> str:
        """Compatibility view for older callers; new code uses the plural field."""
        return self.selected_candidates[0] if self.selected_candidates else ""


# --- the central artifact -------------------------------------------------------


class ImprovementProposal(BaseModel):
    # an RFC-style, evidence-grounded change proposal (design doc section 6.1).
    summary: str
    problem_statement: str
    analysis: OrchestratorAnalysis = Field(default_factory=OrchestratorAnalysis)
    evidence: list[Evidence] = Field(default_factory=list)
    goals: list[str] = Field(default_factory=list)
    non_goals: list[str] = Field(default_factory=list)
    affected_components: list[str] = Field(default_factory=list)
    # Explicit repo-relative file paths, directory prefixes ending in "/", or
    # glob patterns the Writer is authorized to modify.
    allowed_write_paths: list[str] = Field(default_factory=list)
    dependencies: list[str] = Field(default_factory=list)
    tasks: list[ImprovementTask] = Field(default_factory=list)
    # decision inputs (1-5 scores from the LLM; confidence in [0,1]).
    benefit: int
    risk: int
    effort: int
    confidence: float
    # the LLM's proposed decision; the deterministic policy gate has final say.
    decision: Literal["proceed", "abstain", "needs_human"]
    decision_reason: str
    acceptance_criteria: list[AcceptanceCriterion] = Field(default_factory=list)
    # System-level integration/smoke commands for delivering the changed agent package.
    # Generated-code capability tasks live in the separate post-run eval harness.
    delivery_run: list[str] = Field(default_factory=list)
    # Frozen, capability-specific end-to-end runs. The Runner creates each isolated
    # fixture and substitutes {prompt}/{workspace} into the argv command.
    delivery_scenarios: list[DeliveryScenario] = Field(default_factory=list)
    # High-level system requirements the Deliverer checks against the whole-loop diff.
    # Runtime command facts are handled by the deterministic delivery/commit gate.
    delivery_checklist: list[str] = Field(default_factory=list)
    evaluation_plan: EvaluationPlan | None = None
    rollback_plan: str = ""
    alternatives_considered: list[str] = Field(default_factory=list)


class FrozenProposal(BaseModel):
    # an approved proposal, made immutable + hashed so intent can't drift
    # (design doc section 6.2). A substantial change requires a new version.
    proposal_id: str
    proposal_version: int
    proposal_hash: str
    approved_by: str
    approved_at: str
    target_commit: str
    baseline_run_id: str
    proposal: ImprovementProposal
