"""Data contract for the evidence-grounded improvement pipeline.

These Pydantic models are the shared vocabulary every stage speaks (design doc
sections 6.1-6.4). They encode the reliability-first decisions:
  - proposals must cite inspectable Evidence,
  - acceptance criteria declare HOW they're verified (mode + method),
  - benefit/risk/effort/confidence + an explicit proceed/abstain/needs_human
    decision (LLM scores are inputs; a deterministic policy gate decides),
  - a frozen+hashed proposal so approved intent can't silently drift.

Models are ordered so dependencies come before the models that use them (no
forward references needed).
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, model_validator

# --- primitives -----------------------------------------------------------------


class Evidence(BaseModel):
    # every claim must point at something inspectable.
    source_type: Literal["trajectory", "test", "benchmark", "code", "log"]
    reference: str  # e.g. "ours/agent/query.py:52", "traces/run1.jsonl#span3"
    observation: str


class Finding(BaseModel):
    # a verdict's structured note about a change unit (design doc section 8).
    severity: Literal["info", "minor", "major", "blocker"]
    location: str
    description: str
    evidence: str = ""
    required_fix: str = ""
    related_criterion: str = ""  # AcceptanceCriterion.id


class Metric(BaseModel):
    # a measurable target for metric-based acceptance.
    name: str
    direction: Literal["increase", "decrease"]
    min_delta: float = 0.0  # primary: required improvement; guardrail: allowed regression


class ContractClause(BaseModel):
    """One traceable requirement in the shared Writer/Reviewer task contract."""

    id: str
    description: str


class ImprovementTask(BaseModel):
    # One frozen implementation contract in the proposal's DAG. The Writer
    # implements it and the Reviewer audits the same clauses; neither side gets
    # to redefine success during execution.
    id: str
    # Name of the one selected Candidate this Loop's one Task implements.
    candidate: str = ""
    description: str
    rationale: str = ""
    capability_change: str = ""
    required_behaviors: list[ContractClause] = Field(default_factory=list)
    implementation_constraints: list[ContractClause] = Field(default_factory=list)
    invariants: list[ContractClause] = Field(default_factory=list)
    prohibited_shortcuts: list[ContractClause] = Field(default_factory=list)
    affected_components: list[str] = Field(default_factory=list)
    reviewer_focus: list[str] = Field(default_factory=list)
    # Named safety properties that must be covered by assigned executable
    # acceptance criteria. Keep this small and extensible instead of embedding
    # tool-specific checks in the Reviewer prompt.
    required_safety_properties: list[Literal["path_confinement"]] = Field(
        default_factory=list
    )
    dependencies: list[str] = Field(default_factory=list)
    acceptance_criteria_ids: list[str] = Field(default_factory=list)


class AcceptanceCriterion(BaseModel):
    # A traceable, executable delivery/commit condition for the TARGET AGENT SYSTEM
    # change itself—not a benchmark of code generated by that target agent.
    id: str
    description: str
    mode: Literal["red_green", "invariant", "metric_improvement", "non_regression", "manual"]
    check_type: Literal["unit", "integration", "smoke"] = "unit"
    verification: Literal["command", "review", "manual"] = "command"
    command: str = ""
    expected_exit_code: int = 0
    required_output_contains: list[str] = Field(default_factory=list)
    forbidden_output_contains: list[str] = Field(default_factory=list)
    verified_safety_properties: list[Literal["path_confinement"]] = Field(
        default_factory=list
    )
    # rigor of the functional test the Test Agent generates:
    #   full    -> core/framework: happy path + edges + error handling + invariants
    #   focused -> important logic: unit test asserting key values + intermediates
    #   basic   -> simple: one unit test on the main behavior
    # Ignored for metric modes (verified via the runner's external benchmark hook)
    # and manual mode (human-reviewed); the Test Agent does not auto-generate those.
    test_level: Literal["full", "focused", "basic"] = "focused"
    # Compatibility/advisory flag. Deterministic delivery only hard-enforces
    # delivery_run plus criteria carrying an explicit safety property.
    required: bool = False


class EvaluationPlan(BaseModel):
    # the frozen evaluation design: what to run + the metric gates.
    primary_metric: Metric | None = None
    guardrail_metrics: list[Metric] = Field(default_factory=list)
    scenarios: list[str] = Field(default_factory=list)  # test-agent turns these into runs
    run_count: int = 1  # repeat runs for nondeterministic behavior


class ExecutableCondition(BaseModel):
    """One typed runtime condition materialized by the trusted execution tool."""

    name: str = Field(
        min_length=1,
        max_length=64,
        pattern=r"^[A-Za-z0-9][A-Za-z0-9._+-]*$",
    )
    state: Literal["available", "unavailable"]


class DeliveryScenario(BaseModel):
    """Frozen end-to-end prompt executed against the improved target agent."""

    id: str
    prompt: str
    # Safe argv form. Supported placeholders: {prompt} and {workspace}.
    command: list[str]
    fixture_files: dict[str, str] = Field(default_factory=dict)
    expected_behaviors: list[str] = Field(default_factory=list)
    forbidden_behaviors: list[str] = Field(default_factory=list)
    # The Orchestrator declares bounded runtime conditions; the execution tool validates
    # and materializes them without accepting arbitrary env values or setup code.
    executable_conditions: list[ExecutableCondition] = Field(
        default_factory=list,
        max_length=8,
    )
    # Required when acceptance depends on internal tool use, ordering, or another
    # process fact that stdout and final artifacts cannot independently establish.
    requires_trajectory: bool = False


class ReviewResult(BaseModel):
    # the Reviewer's verdict on a change unit.
    verdict: Literal["accept", "revise", "escalate"]
    findings: list[Finding] = Field(default_factory=list)
    summary: str = ""


class ExecutionBlocker(BaseModel):
    # raised when a task can't converge within bounded Writer-Reviewer rounds.
    task_id: str
    review_rounds: int
    unresolved_findings: list[Finding] = Field(default_factory=list)
    attempted_fixes: list[str] = Field(default_factory=list)
    affected_tasks: list[str] = Field(default_factory=list)
    recommendation: Literal["abstain_task", "amend_plan", "request_human", "abort_proposal"]


class DiagnosticFinding(BaseModel):
    """Evidence-backed distinction between a symptom and an underlying capability gap."""

    symptom: str
    root_cause: str
    capability_gap: str
    evidence_refs: list[str] = Field(default_factory=list)
    uncertainty: str = ""


class InterventionCandidate(BaseModel):
    """One alternative considered before the Orchestrator selects a plan."""

    name: str
    level: Literal["prompt", "workflow", "tool", "module", "architecture"]
    # The exact gap this intervention addresses.  This is deliberately narrower
    # than a broad domain such as "tool use" so a delivered slice does not close
    # every future improvement in the same area.
    capability_gap: str = ""
    mechanism: str
    expected_capability_delta: str
    evidence_refs: list[str] = Field(default_factory=list)
    evidence_strength: int = 1
    benefit: int = 1
    risk: int = 1
    effort: int = 1
    dependencies: list[str] = Field(default_factory=list)
    conflicts_with: list[str] = Field(default_factory=list)
    rejected_reason: str = ""


class CandidateDiagnosis(BaseModel):
    """Decision-level evidence for one persistent improvement hypothesis."""

    symptom: str = ""
    root_cause: str = ""
    capability_gap: str
    evidence_refs: list[str] = Field(default_factory=list)
    uncertainty: str = ""


class CandidateIntervention(BaseModel):
    """The causal mechanism proposed for a backlog hypothesis."""

    level: Literal["prompt", "workflow", "tool", "module", "architecture"]
    mechanism: str
    expected_capability_delta: str


class ProblemScorecard(BaseModel):
    """LLM-authored assessment of the problem before solution cost is considered."""

    evidence_strength: int = Field(default=1, ge=1, le=5)
    failure_severity: int = Field(default=1, ge=1, le=5)
    recurrence: int = Field(default=1, ge=1, le=5)
    cross_task_impact: int = Field(default=1, ge=1, le=5)
    evidence_freshness: int = Field(default=1, ge=1, le=5)
    user_relevance: int = Field(default=1, ge=1, le=5)
    assessment: str = ""


class CausalScorecard(BaseModel):
    """How directly the diagnosis and intervention explain the observed problem."""

    root_cause_confidence: int = Field(default=1, ge=1, le=5)
    intervention_fit: int = Field(default=1, ge=1, le=5)
    competing_hypotheses: list[str] = Field(default_factory=list)
    falsification_condition: str = ""


class ImpactScorecard(BaseModel):
    """Expected value and practical cost of the proposed intervention."""

    expected_outcome_impact: int = Field(default=1, ge=1, le=5)
    generality: int = Field(default=1, ge=1, le=5)
    one_loop_feasibility: int = Field(default=1, ge=1, le=5)
    regression_risk: int = Field(default=1, ge=1, le=5)
    effort: int = Field(default=1, ge=1, le=5)
    expected_delta: str = ""


class EvaluabilityScorecard(BaseModel):
    """Whether a real outcome delta can be distinguished from model noise."""

    mechanism_observability: int = Field(default=1, ge=1, le=5)
    outcome_observability: int = Field(default=1, ge=1, le=5)
    discriminability: int = Field(default=1, ge=1, le=5)
    attribution_confidence: int = Field(default=1, ge=1, le=5)
    noise_robustness: int = Field(default=1, ge=1, le=5)
    evaluation_cost: int = Field(default=1, ge=1, le=5)
    baseline_prediction: str = ""
    candidate_prediction: str = ""
    observable_difference: str = ""
    confounders: list[str] = Field(default_factory=list)


class CandidatePriority(BaseModel):
    # These scorecards structure LLM deliberation. They are not combined into a
    # deterministic score and do not participate in a policy gate.
    problem: ProblemScorecard = Field(default_factory=ProblemScorecard)
    causal: CausalScorecard = Field(default_factory=CausalScorecard)
    impact: ImpactScorecard = Field(default_factory=ImpactScorecard)
    evaluability: EvaluabilityScorecard = Field(default_factory=EvaluabilityScorecard)
    # Backward-compatible advisory summary retained for historical records.
    benefit: int = Field(default=1, ge=1, le=5)
    risk: int = Field(default=1, ge=1, le=5)
    effort: int = Field(default=1, ge=1, le=5)
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    rank_reason: str = ""


class CandidateScope(BaseModel):
    affected_components: list[str] = Field(default_factory=list)
    non_goals: list[str] = Field(default_factory=list)


class CandidateHistory(BaseModel):
    first_seen_loop: int = 0
    last_reviewed_loop: int = 0
    previous_attempts: list[str] = Field(default_factory=list)
    verification_scope: list[str] = Field(default_factory=list)
    verification_level: Literal[
        "none", "implemented", "behavior_verified", "delta_demonstrated"
    ] = "none"
    disposition_reason: str = ""


class BacklogCandidate(BaseModel):
    """A complete decision-level todo, keyed by a stable id in the backlog."""

    id: str
    status: Literal["open", "deferred", "attempt_failed", "behavior_verified"] = "open"
    title: str
    diagnosis: CandidateDiagnosis
    intervention: CandidateIntervention
    priority: CandidatePriority = Field(default_factory=CandidatePriority)
    scope: CandidateScope = Field(default_factory=CandidateScope)
    dependencies: list[str] = Field(default_factory=list)
    conflicts_with: list[str] = Field(default_factory=list)
    history: CandidateHistory = Field(default_factory=CandidateHistory)


class CandidateRankingEntry(BaseModel):
    """One LLM-authored position in the preliminary Candidate ranking."""

    candidate_id: str
    rank: int = Field(ge=1)
    rationale: str


class CandidatePairwiseComparison(BaseModel):
    """A qualitative Top-2 review; ``DEFER`` may be the second option."""

    candidate_a: str
    candidate_b: str
    strongest_case_for_a: str
    strongest_case_for_b: str
    # Flexible named judgments such as evidence, causal fit, outcome delta,
    # observability, and risk/effort. Values explain which side has the advantage.
    comparative_judgments: dict[str, str] = Field(default_factory=dict)
    baseline_counterfactual: str = ""
    candidate_counterfactual: str = ""
    winner: str
    decision_reason: str


class AlertDisposition(BaseModel):
    """Triage's explicit accounting for one current-version run alert."""

    run_id: str
    observed_failure: str
    agent_level_interpretation: str
    likely_causes: list[str] = Field(default_factory=list)
    disposition: Literal[
        "candidate_problem",
        "deferred",
        "unsupported",
        "already_resolved",
    ]
    disposition_reason: str
    evidence_refs: list[str] = Field(default_factory=list)


class ProblemCase(BaseModel):
    """An evidence-grounded problem, intentionally separated from its solution."""

    id: str
    symptom: str
    capability_gap: str
    likely_root_causes: list[str] = Field(default_factory=list)
    affected_scope: list[str] = Field(default_factory=list)
    evidence_refs: list[str] = Field(default_factory=list)
    uncertainty: str = ""


class DiagnosisBoard(BaseModel):
    """Stage-one artifact: evidence dispositions and agent-level problems."""

    alert_dispositions: list[AlertDisposition] = Field(default_factory=list)
    problem_cases: dict[str, ProblemCase] = Field(default_factory=dict)
    retired_problems: dict[str, str] = Field(default_factory=dict)
    whole_picture_summary: str = ""


class SelectionDecision(BaseModel):
    """Stage-two artifact: candidate generation, ranking, and one selection."""

    summary: str
    problem_statement: str
    candidate_backlog: dict[str, BacklogCandidate] = Field(default_factory=dict)
    preliminary_ranking: list[CandidateRankingEntry] = Field(default_factory=list)
    top_two_comparison: CandidatePairwiseComparison | None = None
    selected_candidate_id: str = ""
    deferred_candidates: dict[str, str] = Field(default_factory=dict)
    benefit: int = Field(ge=1, le=5)
    risk: int = Field(ge=1, le=5)
    effort: int = Field(ge=1, le=5)
    confidence: float = Field(ge=0, le=1)
    decision: Literal["proceed", "abstain", "needs_human"]
    decision_reason: str


class OrchestratorArtifacts(BaseModel):
    """Auditable internal artifacts from the logical three-stage Orchestrator."""

    diagnosis: DiagnosisBoard
    selection: SelectionDecision


class SelectedChangeContract(BaseModel):
    """The one frozen execution contract selected for this Loop."""

    contract_id: str
    backlog_item_id: str
    backlog_revision: int = Field(default=1, ge=1)
    objective: str
    rationale: str = ""
    diagnosis: CandidateDiagnosis
    intervention: CandidateIntervention
    inputs: list[ContractClause] = Field(default_factory=list)
    expected_outputs: list[ContractClause] = Field(default_factory=list)
    required_behaviors: list[ContractClause] = Field(default_factory=list)
    implementation_constraints: list[ContractClause] = Field(default_factory=list)
    invariants: list[ContractClause] = Field(default_factory=list)
    prohibited_shortcuts: list[ContractClause] = Field(default_factory=list)
    affected_components: list[str] = Field(default_factory=list)
    allowed_write_paths: list[str] = Field(default_factory=list)
    reviewer_focus: list[str] = Field(default_factory=list)
    required_safety_properties: list[Literal["path_confinement"]] = Field(
        default_factory=list
    )
    acceptance_criteria: list[AcceptanceCriterion] = Field(default_factory=list)
    delivery_run: list[str] = Field(default_factory=list)
    delivery_scenarios: list[DeliveryScenario] = Field(default_factory=list)
    delivery_checklist: list[str] = Field(default_factory=list)
    rollback_plan: str = ""

    def as_task(self) -> ImprovementTask:
        """Compatibility view for the existing serial Writer/Reviewer executor."""

        return ImprovementTask(
            id=self.contract_id,
            candidate=self.backlog_item_id,
            description=self.objective,
            rationale=self.rationale,
            capability_change=self.intervention.expected_capability_delta,
            required_behaviors=[*self.inputs, *self.expected_outputs, *self.required_behaviors],
            implementation_constraints=self.implementation_constraints,
            invariants=self.invariants,
            prohibited_shortcuts=self.prohibited_shortcuts,
            affected_components=self.affected_components,
            reviewer_focus=self.reviewer_focus,
            required_safety_properties=self.required_safety_properties,
            dependencies=[],
            acceptance_criteria_ids=[
                criterion.id for criterion in self.acceptance_criteria
            ],
        )


class ContractExpansion(BaseModel):
    """Stage-three artifact; the coordinator joins it with frozen Selection."""

    proposal_guardrails: list[ContractClause] = Field(default_factory=list)
    selected_change_contract: SelectedChangeContract
    evidence: list[Evidence] = Field(default_factory=list)
    goals: list[str] = Field(default_factory=list)
    non_goals: list[str] = Field(default_factory=list)
    affected_components: list[str] = Field(default_factory=list)
    dependencies: list[str] = Field(default_factory=list)
    alternatives_considered: list[str] = Field(default_factory=list)


class ImprovementBatchBudget(BaseModel):
    """Compatibility metadata for the one-Candidate/one-Task Loop budget."""

    max_candidates: int = Field(default=1, ge=1, le=3)
    max_tasks: int = Field(default=1, ge=1, le=6)
    max_total_effort: int = Field(default=6, ge=1, le=6)
    selected_total_effort: int = Field(default=0, ge=0, le=6)


class OrchestratorAnalysis(BaseModel):
    """Diagnosis plus selection of one Candidate for the next Loop."""

    findings: list[DiagnosticFinding] = Field(default_factory=list)
    candidates: list[InterventionCandidate] = Field(default_factory=list)
    selected_candidates: list[str] = Field(default_factory=list)
    batch_budget: ImprovementBatchBudget = Field(default_factory=ImprovementBatchBudget)
    packing_reason: str = ""
    compatibility_notes: list[str] = Field(default_factory=list)
    selection_reason: str = ""
    causal_mechanism: str = ""
    expected_capability_delta: str = ""

    @model_validator(mode="before")
    @classmethod
    def migrate_singular_selection(cls, value):
        """Read older proposal JSON that used ``selected_candidate``."""
        if isinstance(value, dict):
            data = dict(value)
            if not data.get("selected_candidates") and data.get("selected_candidate"):
                data["selected_candidates"] = [str(data["selected_candidate"])]
            return data
        return value

    @property
    def selected_candidate(self) -> str:
        """Compatibility view for older callers; new code uses the plural field."""
        return self.selected_candidates[0] if self.selected_candidates else ""


# --- the central artifact -------------------------------------------------------


class ImprovementProposal(BaseModel):
    # an RFC-style, evidence-grounded change proposal (design doc section 6.1).
    summary: str
    problem_statement: str
    # Whole-picture boundaries. Implementations may deviate from suggested paths,
    # but Writer/Reviewer/Deliverer must not violate these clauses.
    proposal_guardrails: list[ContractClause] = Field(default_factory=list)
    # New decision interface. Backlog items are decision-level hypotheses; only the
    # selected item is expanded into an execution-level contract.
    candidate_backlog: dict[str, BacklogCandidate] = Field(default_factory=dict)
    # LLM-authored decision artifacts. The framework records their structure but
    # does not calculate a score or override the model's qualitative judgment.
    preliminary_ranking: list[CandidateRankingEntry] = Field(default_factory=list)
    top_two_comparison: CandidatePairwiseComparison | None = None
    selected_candidate_id: str = ""
    selected_change_contract: SelectedChangeContract | None = None
    # Added by the Orchestrator coordinator after contract expansion. The LLM
    # that expands the contract does not need to reproduce these artifacts.
    orchestrator_artifacts: OrchestratorArtifacts | None = None
    # Legacy analysis/task fields remain readable while stored runs migrate.
    analysis: OrchestratorAnalysis = Field(default_factory=OrchestratorAnalysis)
    evidence: list[Evidence] = Field(default_factory=list)
    goals: list[str] = Field(default_factory=list)
    non_goals: list[str] = Field(default_factory=list)
    affected_components: list[str] = Field(default_factory=list)
    # Explicit repo-relative file paths, directory prefixes ending in "/", or
    # glob patterns the Writer is authorized to modify.
    allowed_write_paths: list[str] = Field(default_factory=list)
    dependencies: list[str] = Field(default_factory=list)
    tasks: list[ImprovementTask] = Field(default_factory=list)
    # decision inputs (1-5 scores from the LLM; confidence in [0,1]).
    benefit: int
    risk: int
    effort: int
    confidence: float
    # the LLM's proposed decision; the deterministic policy gate has final say.
    decision: Literal["proceed", "abstain", "needs_human"]
    decision_reason: str
    acceptance_criteria: list[AcceptanceCriterion] = Field(default_factory=list)
    # System-level integration/smoke commands for delivering the changed agent package.
    # Generated-code capability tasks live in the separate post-run eval harness.
    delivery_run: list[str] = Field(default_factory=list)
    # Frozen, capability-specific end-to-end runs. The Deliverer chooses when to invoke
    # them; the execution tool creates an isolated fixture and substitutes only the
    # placeholders explicitly present in the argv command.
    delivery_scenarios: list[DeliveryScenario] = Field(default_factory=list)
    # High-level system requirements the Deliverer checks against the whole-loop diff.
    # Runtime facts are gathered by Deliverer tools; universal failures remain hard gates.
    delivery_checklist: list[str] = Field(default_factory=list)
    evaluation_plan: EvaluationPlan | None = None
    rollback_plan: str = ""
    alternatives_considered: list[str] = Field(default_factory=list)

    def execution_contract(self) -> SelectedChangeContract | None:
        """Return the canonical contract, synthesizing old Proposal records lazily."""

        if self.selected_change_contract is not None:
            return self.selected_change_contract
        if not self.tasks:
            return None
        task = self.tasks[0]
        selected_name = (
            self.analysis.selected_candidate or task.candidate or task.id
        )
        candidate = next(
            (
                item
                for item in self.analysis.candidates
                if item.name == selected_name
            ),
            None,
        )
        finding = self.analysis.findings[0] if self.analysis.findings else None
        capability_gap = (
            candidate.capability_gap
            if candidate and candidate.capability_gap
            else finding.capability_gap
            if finding
            else task.capability_change or task.description
        )
        diagnosis = CandidateDiagnosis(
            symptom=finding.symptom if finding else "",
            root_cause=finding.root_cause if finding else task.rationale,
            capability_gap=capability_gap,
            evidence_refs=(
                candidate.evidence_refs
                if candidate and candidate.evidence_refs
                else finding.evidence_refs
                if finding
                else []
            ),
            uncertainty=finding.uncertainty if finding else "",
        )
        intervention = CandidateIntervention(
            level=candidate.level if candidate else "workflow",
            mechanism=(
                self.analysis.causal_mechanism
                or candidate.mechanism
                if candidate
                else self.analysis.causal_mechanism or task.rationale or task.description
            ),
            expected_capability_delta=(
                candidate.expected_capability_delta
                if candidate
                else self.analysis.expected_capability_delta
                or task.capability_change
                or task.description
            ),
        )
        return SelectedChangeContract(
            contract_id=task.id,
            backlog_item_id=selected_name,
            objective=task.description,
            rationale=task.rationale,
            diagnosis=diagnosis,
            intervention=intervention,
            required_behaviors=task.required_behaviors,
            implementation_constraints=task.implementation_constraints,
            invariants=task.invariants,
            prohibited_shortcuts=task.prohibited_shortcuts,
            affected_components=task.affected_components,
            allowed_write_paths=self.allowed_write_paths,
            reviewer_focus=task.reviewer_focus,
            required_safety_properties=task.required_safety_properties,
            acceptance_criteria=[
                criterion
                for criterion in self.acceptance_criteria
                if criterion.id in task.acceptance_criteria_ids
            ],
            delivery_run=self.delivery_run,
            delivery_scenarios=self.delivery_scenarios,
            delivery_checklist=self.delivery_checklist,
            rollback_plan=self.rollback_plan,
        )

    def execution_tasks(self) -> list[ImprovementTask]:
        if self.selected_change_contract is not None:
            task = self.selected_change_contract.as_task()
            # Proposal guardrails are projected into the shared Writer/Reviewer
            # invariant view. They remain whole-picture boundaries rather than
            # implementation prescriptions.
            return [
                task.model_copy(
                    update={
                        "invariants": [
                            *self.proposal_guardrails,
                            *task.invariants,
                        ]
                    }
                )
            ]
        return self.tasks

    def contract_acceptance_criteria(self) -> list[AcceptanceCriterion]:
        if self.selected_change_contract is not None:
            return self.selected_change_contract.acceptance_criteria
        return self.acceptance_criteria

    def contract_delivery_run(self) -> list[str]:
        if self.selected_change_contract is not None:
            return self.selected_change_contract.delivery_run
        return self.delivery_run

    def contract_delivery_scenarios(self) -> list[DeliveryScenario]:
        if self.selected_change_contract is not None:
            return self.selected_change_contract.delivery_scenarios
        return self.delivery_scenarios

    def contract_allowed_write_paths(self) -> list[str]:
        if self.selected_change_contract is not None:
            return self.selected_change_contract.allowed_write_paths
        return self.allowed_write_paths


class FrozenProposal(BaseModel):
    # an approved proposal, made immutable + hashed so intent can't drift
    # (design doc section 6.2). A substantial change requires a new version.
    proposal_id: str
    proposal_version: int
    proposal_hash: str
    approved_by: str
    approved_at: str
    target_commit: str
    baseline_run_id: str
    proposal: ImprovementProposal
