"""Data contract for the evidence-grounded improvement pipeline.

These Pydantic models are the shared vocabulary every stage speaks (design doc
sections 6.1-6.4). They encode the reliability-first decisions:
  - proposals must cite inspectable Evidence,
  - acceptance criteria declare HOW they're verified (mode + method),
  - benefit/risk/effort/confidence + an explicit proceed/abstain/needs_human
    decision (LLM scores are inputs; a deterministic policy gate decides),
  - a frozen+hashed proposal so approved intent can't silently drift.

Models are ordered so dependencies come before the models that use them (no
forward references needed).
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, model_validator

# --- primitives -----------------------------------------------------------------


class Evidence(BaseModel):
    # every claim must point at something inspectable.
    source_type: Literal["trajectory", "test", "benchmark", "code", "log"]
    reference: str  # e.g. "ours/agent/query.py:52", "traces/run1.jsonl#span3"
    observation: str


class Finding(BaseModel):
    # a verdict's structured note about a change unit (design doc section 8).
    id: str = ""
    severity: Literal["info", "minor", "major", "blocker"]
    location: str
    description: str
    evidence: str = ""
    required_fix: str = ""
    related_criterion: str = ""  # AcceptanceCriterion.id


class Metric(BaseModel):
    # a measurable target for metric-based acceptance.
    name: str
    direction: Literal["increase", "decrease"]
    min_delta: float = 0.0  # primary: required improvement; guardrail: allowed regression


class ContractClause(BaseModel):
    """One traceable requirement in the shared Writer/Reviewer task contract."""

    id: str
    description: str


class ImprovementTask(BaseModel):
    # One frozen implementation contract in the proposal's DAG. The Writer
    # implements it and the Reviewer audits the same clauses; neither side gets
    # to redefine success during execution.
    id: str
    # Name of the one selected Candidate this Loop's one Task implements.
    candidate: str = ""
    description: str
    rationale: str = ""
    capability_change: str = ""
    required_behaviors: list[ContractClause] = Field(default_factory=list)
    implementation_constraints: list[ContractClause] = Field(default_factory=list)
    invariants: list[ContractClause] = Field(default_factory=list)
    prohibited_shortcuts: list[ContractClause] = Field(default_factory=list)
    affected_components: list[str] = Field(default_factory=list)
    reviewer_focus: list[str] = Field(default_factory=list)
    # Named safety properties that must be covered by assigned executable
    # acceptance criteria. Keep this small and extensible instead of embedding
    # tool-specific checks in the Reviewer prompt.
    required_safety_properties: list[Literal["path_confinement"]] = Field(
        default_factory=list
    )
    dependencies: list[str] = Field(default_factory=list)
    acceptance_criteria_ids: list[str] = Field(default_factory=list)


class WriterAcceptanceCheck(BaseModel):
    """Compact executable/review direction included in the Writer task view."""

    id: str
    description: str
    verification: Literal["command", "review", "manual"]


class WriterTaskContract(BaseModel):
    """Minimal execution view compiled from the auditable Change Contract."""

    contract_id: str
    objective: str
    capability_delta: str = ""
    implementation_direction: str = ""
    requirements: list[ContractClause] = Field(default_factory=list, max_length=5)
    constraints: list[ContractClause] = Field(default_factory=list, max_length=4)
    non_goals: list[ContractClause] = Field(default_factory=list, max_length=3)
    suggested_components: list[str] = Field(default_factory=list, max_length=6)
    required_safety_properties: list[Literal["path_confinement"]] = Field(
        default_factory=list
    )
    acceptance_checks: list[WriterAcceptanceCheck] = Field(
        default_factory=list,
        max_length=3,
    )


class AcceptanceCriterion(BaseModel):
    # A traceable, executable delivery/commit condition for the TARGET AGENT SYSTEM
    # change itself—not a benchmark of code generated by that target agent.
    id: str
    description: str
    mode: Literal["red_green", "invariant", "metric_improvement", "non_regression", "manual"]
    check_type: Literal["unit", "integration", "smoke"] = "unit"
    verification: Literal["command", "review", "manual"] = "command"
    command: str = ""
    expected_exit_code: int = 0
    required_output_contains: list[str] = Field(default_factory=list)
    forbidden_output_contains: list[str] = Field(default_factory=list)
    verified_safety_properties: list[Literal["path_confinement"]] = Field(
        default_factory=list
    )
    # rigor of the functional test the Test Agent generates:
    #   full    -> core/framework: happy path + edges + error handling + invariants
    #   focused -> important logic: unit test asserting key values + intermediates
    #   basic   -> simple: one unit test on the main behavior
    # Ignored for metric modes (verified via the runner's external benchmark hook)
    # and manual mode (human-reviewed); the Test Agent does not auto-generate those.
    test_level: Literal["full", "focused", "basic"] = "focused"
    # Compatibility/advisory flag. Deterministic delivery only hard-enforces
    # delivery_run plus criteria carrying an explicit safety property.
    required: bool = False


class EvaluationPlan(BaseModel):
    # the frozen evaluation design: what to run + the metric gates.
    primary_metric: Metric | None = None
    guardrail_metrics: list[Metric] = Field(default_factory=list)
    scenarios: list[str] = Field(default_factory=list)  # test-agent turns these into runs
    run_count: int = 1  # repeat runs for nondeterministic behavior


class ExecutableCondition(BaseModel):
    """One typed runtime condition materialized by the trusted execution tool."""

    name: str = Field(
        min_length=1,
        max_length=64,
        pattern=r"^[A-Za-z0-9][A-Za-z0-9._+-]*$",
    )
    state: Literal["available", "unavailable"]


class ScenarioOutcomeCondition(BaseModel):
    """One explained, directional outcome used by the Deliverer."""

    id: str
    description: str
    rationale: str
    evidence_direction: str


class ScenarioOutcomeContract(BaseModel):
    """Separate proof of success from guardrails and inconclusive outcomes."""

    primary_success: list[ScenarioOutcomeCondition] = Field(min_length=1)
    guardrails: list[ScenarioOutcomeCondition] = Field(default_factory=list)
    inconclusive: list[ScenarioOutcomeCondition] = Field(default_factory=list)


class ScenarioTaskContract(BaseModel):
    """Structured task given to the target agent during Delivery."""

    objective: str
    context: list[str] = Field(default_factory=list)
    requirements: list[ContractClause] = Field(default_factory=list)
    constraints: list[ContractClause] = Field(default_factory=list)
    outcome_contract: ScenarioOutcomeContract
    acceptance_checks: list[ContractClause] = Field(default_factory=list)

    @model_validator(mode="before")
    @classmethod
    def migrate_legacy_expected_outputs(cls, value):
        if not isinstance(value, dict) or "outcome_contract" in value:
            return value
        migrated = dict(value)
        outputs = migrated.pop("expected_outputs", [])
        primary = [
            {
                "id": str(item.get("id") or f"legacy-{index}"),
                "description": str(item.get("description") or ""),
                "rationale": "Migrated legacy expected output.",
                "evidence_direction": (
                    "Observed output/artifact evidence should support this result."
                ),
            }
            for index, item in enumerate(outputs, start=1)
            if isinstance(item, dict)
        ]
        if not primary:
            objective = str(migrated.get("objective") or "Complete the task.")
            primary = [
                {
                    "id": "legacy-primary",
                    "description": objective,
                    "rationale": "Migrated legacy Scenario objective.",
                    "evidence_direction": (
                        "Observed trajectory and artifacts should demonstrate completion."
                    ),
                }
            ]
        migrated["outcome_contract"] = {
            "primary_success": primary,
            "guardrails": [],
            "inconclusive": [],
        }
        return migrated

    def render_prompt(self) -> str:
        """Render the form into a stable human-readable target-agent prompt."""

        sections = [f"Objective:\n{self.objective.strip()}"]
        groups = (
            ("Context", self.context),
            (
                "Requirements",
                [f"[{item.id}] {item.description}" for item in self.requirements],
            ),
            (
                "Constraints",
                [f"[{item.id}] {item.description}" for item in self.constraints],
            ),
            (
                "Primary success conditions",
                [
                    (
                        f"[{item.id}] {item.description}\n"
                        f"  Why: {item.rationale}\n"
                        f"  Evidence direction: {item.evidence_direction}"
                    )
                    for item in self.outcome_contract.primary_success
                ],
            ),
            (
                "Guardrail conditions",
                [
                    (
                        f"[{item.id}] {item.description}\n"
                        f"  Why: {item.rationale}\n"
                        f"  Evidence direction: {item.evidence_direction}"
                    )
                    for item in self.outcome_contract.guardrails
                ],
            ),
            (
                "Inconclusive conditions",
                [
                    (
                        f"[{item.id}] {item.description}\n"
                        f"  Why: {item.rationale}\n"
                        f"  Evidence direction: {item.evidence_direction}"
                    )
                    for item in self.outcome_contract.inconclusive
                ],
            ),
            (
                "Acceptance checks",
                [f"[{item.id}] {item.description}" for item in self.acceptance_checks],
            ),
        )
        for title, items in groups:
            if items:
                sections.append(title + ":\n" + "\n".join(f"- {item}" for item in items))
        return "\n\n".join(sections)


class ScenarioObservation(BaseModel):
    """One behavior the Deliverer should inspect in target-agent evidence."""

    id: str
    component: str
    expected_behavior: str
    evidence_sources: list[
        Literal[
            "agent_input",
            "agent_output",
            "tool_call",
            "tool_result",
            "artifact",
            "final_output",
            "log",
        ]
    ] = Field(default_factory=list)


class ScenarioBudgets(BaseModel):
    """Separate loop-safety and meaningful-action budgets for a target run."""

    max_agent_turns: int = Field(default=20, ge=1, le=100)
    max_action_steps: int = Field(default=8, ge=1, le=50)


class DeliveryScenario(BaseModel):
    """One frozen end-to-end task run against the improved target agent.

    A Scenario owns one disposable TASK WORKSPACE.  It is evidence about the
    AGENT UNDER IMPROVEMENT, never a request to add the fixture's business
    feature to the agent repository itself.
    """

    id: str
    task_contract: ScenarioTaskContract
    # Safe argv form. Supported placeholders: {prompt} and {workspace}.
    command: list[str]
    fixture_files: dict[str, str] = Field(default_factory=dict)
    # Prompt-authored, provider-neutral facts needed to interpret the fixture.
    # Executable availability remains typed separately below.
    environment_requirements: list[str] = Field(default_factory=list)
    baseline_prediction: str = ""
    candidate_prediction: str = ""
    observable_difference: str = ""
    expected_behaviors: list[str] = Field(default_factory=list)
    forbidden_behaviors: list[str] = Field(default_factory=list)
    observations: list[ScenarioObservation] = Field(default_factory=list)
    budgets: ScenarioBudgets = Field(default_factory=ScenarioBudgets)
    # The Orchestrator declares bounded runtime conditions; the execution tool validates
    # and materializes them without accepting arbitrary env values or setup code.
    executable_conditions: list[ExecutableCondition] = Field(
        default_factory=list,
        max_length=8,
    )
    # Required when acceptance depends on internal tool use, ordering, or another
    # process fact that stdout and final artifacts cannot independently establish.
    requires_trajectory: bool = False

    @model_validator(mode="before")
    @classmethod
    def migrate_legacy_prompt(cls, value):
        """Load old records while making new schema output task-contract shaped."""

        if not isinstance(value, dict) or "task_contract" in value:
            return value
        prompt = str(value.get("prompt") or "").strip()
        if not prompt:
            return value
        migrated = dict(value)
        migrated.pop("prompt", None)
        migrated["task_contract"] = {"objective": prompt}
        return migrated

    def render_prompt(self) -> str:
        return self.task_contract.render_prompt()


class ReviewResult(BaseModel):
    # the Reviewer's verdict on a change unit.
    verdict: Literal["accept", "revise", "escalate"]
    findings: list[Finding] = Field(default_factory=list)
    summary: str = ""


class ExecutionBlocker(BaseModel):
    # raised when a task can't converge within bounded Writer-Reviewer rounds.
    task_id: str
    review_rounds: int
    unresolved_findings: list[Finding] = Field(default_factory=list)
    attempted_fixes: list[str] = Field(default_factory=list)
    affected_tasks: list[str] = Field(default_factory=list)
    recommendation: Literal["abstain_task", "amend_plan", "request_human", "abort_proposal"]


class DiagnosticFinding(BaseModel):
    """Evidence-backed distinction between a symptom and an underlying capability gap."""

    symptom: str
    root_cause: str
    capability_gap: str
    evidence_refs: list[str] = Field(default_factory=list)
    uncertainty: str = ""


class InterventionCandidate(BaseModel):
    """One alternative considered before the Orchestrator selects a plan."""

    name: str
    level: Literal["prompt", "workflow", "tool", "module", "architecture"]
    # The exact gap this intervention addresses.  This is deliberately narrower
    # than a broad domain such as "tool use" so a delivered slice does not close
    # every future improvement in the same area.
    capability_gap: str = ""
    mechanism: str
    expected_capability_delta: str
    evidence_refs: list[str] = Field(default_factory=list)
    evidence_strength: int = 1
    benefit: int = 1
    risk: int = 1
    effort: int = 1
    dependencies: list[str] = Field(default_factory=list)
    conflicts_with: list[str] = Field(default_factory=list)
    rejected_reason: str = ""


class CandidateDiagnosis(BaseModel):
    """Decision-level evidence for one persistent improvement hypothesis."""

    symptom: str = ""
    root_cause: str = ""
    capability_gap: str
    evidence_refs: list[str] = Field(default_factory=list)
    uncertainty: str = ""


class CandidateIntervention(BaseModel):
    """The causal mechanism proposed for a backlog hypothesis."""

    level: Literal["prompt", "workflow", "tool", "module", "architecture"]
    mechanism: str
    expected_capability_delta: str


class ProblemScorecard(BaseModel):
    """LLM-authored assessment of the problem before solution cost is considered."""

    evidence_strength: int = Field(default=1, ge=1, le=5)
    failure_severity: int = Field(default=1, ge=1, le=5)
    recurrence: int = Field(default=1, ge=1, le=5)
    cross_task_impact: int = Field(default=1, ge=1, le=5)
    evidence_freshness: int = Field(default=1, ge=1, le=5)
    user_relevance: int = Field(default=1, ge=1, le=5)
    assessment: str = ""


class CausalScorecard(BaseModel):
    """How directly the diagnosis and intervention explain the observed problem."""

    root_cause_confidence: int = Field(default=1, ge=1, le=5)
    intervention_fit: int = Field(default=1, ge=1, le=5)
    competing_hypotheses: list[str] = Field(default_factory=list)
    falsification_condition: str = ""


class ImpactScorecard(BaseModel):
    """Expected value and practical cost of the proposed intervention."""

    expected_outcome_impact: int = Field(default=1, ge=1, le=5)
    generality: int = Field(default=1, ge=1, le=5)
    one_loop_feasibility: int = Field(default=1, ge=1, le=5)
    regression_risk: int = Field(default=1, ge=1, le=5)
    effort: int = Field(default=1, ge=1, le=5)
    expected_delta: str = ""


class EvaluabilityScorecard(BaseModel):
    """Whether a real outcome delta can be distinguished from model noise."""

    mechanism_observability: int = Field(default=1, ge=1, le=5)
    outcome_observability: int = Field(default=1, ge=1, le=5)
    discriminability: int = Field(default=1, ge=1, le=5)
    attribution_confidence: int = Field(default=1, ge=1, le=5)
    noise_robustness: int = Field(default=1, ge=1, le=5)
    evaluation_cost: int = Field(default=1, ge=1, le=5)
    baseline_prediction: str = ""
    candidate_prediction: str = ""
    observable_difference: str = ""
    confounders: list[str] = Field(default_factory=list)


class CandidatePriority(BaseModel):
    # These scorecards structure LLM deliberation. They are not combined into a
    # deterministic score and do not participate in a policy gate.
    problem: ProblemScorecard = Field(default_factory=ProblemScorecard)
    causal: CausalScorecard = Field(default_factory=CausalScorecard)
    impact: ImpactScorecard = Field(default_factory=ImpactScorecard)
    evaluability: EvaluabilityScorecard = Field(default_factory=EvaluabilityScorecard)
    # Backward-compatible advisory summary retained for historical records.
    benefit: int = Field(default=1, ge=1, le=5)
    risk: int = Field(default=1, ge=1, le=5)
    effort: int = Field(default=1, ge=1, le=5)
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    rank_reason: str = ""


class CandidateScope(BaseModel):
    affected_components: list[str] = Field(default_factory=list)
    non_goals: list[str] = Field(default_factory=list)


class CandidateHistory(BaseModel):
    first_seen_loop: int = 0
    last_reviewed_loop: int = 0
    previous_attempts: list[str] = Field(default_factory=list)
    verification_scope: list[str] = Field(default_factory=list)
    verification_level: Literal[
        "none", "implemented", "behavior_verified", "delta_demonstrated"
    ] = "none"
    disposition_reason: str = ""


class BacklogCandidate(BaseModel):
    """A complete decision-level todo, keyed by a stable id in the backlog."""

    id: str
    status: Literal["open", "deferred", "attempt_failed", "behavior_verified"] = "open"
    title: str
    diagnosis: CandidateDiagnosis
    intervention: CandidateIntervention
    priority: CandidatePriority = Field(default_factory=CandidatePriority)
    scope: CandidateScope = Field(default_factory=CandidateScope)
    dependencies: list[str] = Field(default_factory=list)
    conflicts_with: list[str] = Field(default_factory=list)
    history: CandidateHistory = Field(default_factory=CandidateHistory)


class CandidateRankingEntry(BaseModel):
    """One LLM-authored position in the preliminary Candidate ranking."""

    candidate_id: str
    rank: int = Field(ge=1)
    rationale: str


class CandidatePairwiseComparison(BaseModel):
    """A qualitative Top-2 review; ``DEFER`` may be the second option."""

    candidate_a: str
    candidate_b: str
    strongest_case_for_a: str
    strongest_case_for_b: str
    # Flexible named judgments such as evidence, causal fit, outcome delta,
    # observability, and risk/effort. Values explain which side has the advantage.
    comparative_judgments: dict[str, str] = Field(default_factory=dict)
    baseline_counterfactual: str = ""
    candidate_counterfactual: str = ""
    winner: str
    decision_reason: str


class AlertDisposition(BaseModel):
    """Triage's explicit accounting for one current-version run alert."""

    run_id: str
    observed_failure: str
    agent_level_interpretation: str
    likely_causes: list[str] = Field(default_factory=list)
    disposition: Literal[
        "candidate_problem",
        "deferred",
        "unsupported",
        "already_resolved",
    ]
    disposition_reason: str
    evidence_refs: list[str] = Field(default_factory=list)


class ProblemCase(BaseModel):
    """An evidence-grounded problem, intentionally separated from its solution."""

    id: str
    symptom: str
    capability_gap: str
    likely_root_causes: list[str] = Field(default_factory=list)
    affected_scope: list[str] = Field(default_factory=list)
    evidence_refs: list[str] = Field(default_factory=list)
    uncertainty: str = ""


class DiagnosisBoard(BaseModel):
    """Target-analysis artifact: target evidence dispositions and capability problems."""

    alert_dispositions: list[AlertDisposition] = Field(default_factory=list)
    problem_cases: dict[str, ProblemCase] = Field(default_factory=dict)
    retired_problems: dict[str, str] = Field(default_factory=dict)
    whole_picture_summary: str = ""


class WorkflowLoopAssessment(BaseModel):
    """One assessment of AgentReforge's own execution, never target behavior."""

    loop_id: str
    stage: str
    classification: Literal[
        "delivered",
        "target_attempt_failed",
        "workflow_interface_failed",
        "workflow_execution_failed",
        "mixed",
        "inconclusive",
    ]
    observed_facts: list[str] = Field(default_factory=list)
    related_candidate_ids: list[str] = Field(default_factory=list)
    explanation: str


class WorkflowDiagnosisBoard(BaseModel):
    """AgentReforge-process analysis kept outside target Candidate generation."""

    loop_assessments: list[WorkflowLoopAssessment] = Field(default_factory=list)
    workflow_issues: dict[str, ProblemCase] = Field(default_factory=dict)
    target_candidate_exclusions: dict[str, str] = Field(default_factory=dict)
    whole_picture_summary: str = ""


class CaseTaskIntent(BaseModel):
    """The task the target agent was asked to realize in one observed run."""

    objective: str
    requirements: list[str] = Field(default_factory=list)


class CaseArtifactAnalysis(BaseModel):
    """A behavior-level translation of the code/artifacts produced in one run."""

    summary: str
    changed_components: list[str] = Field(default_factory=list)
    implemented_behavior: list[str] = Field(default_factory=list)
    behavior_flow: list[str] = Field(default_factory=list)


class CaseStepAssessment(BaseModel):
    """One ordered target-agent action or outcome checkpoint."""

    step: str
    expected: str
    observed: str
    status: Literal["satisfied", "failed", "partial", "not_observed"]
    evidence_refs: list[str] = Field(default_factory=list)


class CaseCauseHypothesis(BaseModel):
    """One falsifiable explanation for the observed case outcome."""

    hypothesis: str
    evidence_for: list[str] = Field(default_factory=list)
    evidence_against: list[str] = Field(default_factory=list)


class CaseCausalAnalysis(BaseModel):
    """Keep artifact, agent, environment, and workflow ownership distinct."""

    failure_layer: Literal[
        "target_agent",
        "generated_artifact",
        "task_definition",
        "environment",
        "agentreforge_workflow",
        "none",
        "uncertain",
    ]
    direct_cause: str = ""
    contributing_causes: list[str] = Field(default_factory=list)
    alternative_hypotheses: list[CaseCauseHypothesis] = Field(default_factory=list)
    uncertainty: str = ""


class CaseCapabilitySignal(BaseModel):
    """Evidence from one case that may or may not generalize to agent capability."""

    capability: str
    signal: Literal["positive", "negative", "uncertain"]
    evidence_refs: list[str] = Field(default_factory=list)
    generalizability: str = ""


class CaseImprovementOpportunity(BaseModel):
    """A possible improvement area, not yet a selected intervention."""

    area: str
    rationale: str
    expected_effect: str = ""


class CaseAnalysis(BaseModel):
    """Structured interpretation of one target-agent run and its artifacts."""

    case_id: str
    run_id: str
    target_commit: str = ""
    task_intent: CaseTaskIntent
    artifact_analysis: CaseArtifactAnalysis
    final_status: Literal["success", "partial", "failed", "inconclusive"]
    steps: list[CaseStepAssessment] = Field(default_factory=list)
    final_outcome: str
    causal_analysis: CaseCausalAnalysis
    capability_signals: list[CaseCapabilitySignal] = Field(default_factory=list)
    improvement_opportunities: list[CaseImprovementOpportunity] = Field(
        default_factory=list
    )


class CaseAnalysisBoard(BaseModel):
    """Deterministically assembled collection of independently analyzed runs."""

    cases: dict[str, CaseAnalysis] = Field(default_factory=dict)


class SelectionDecision(BaseModel):
    """Stage-two artifact: candidate generation, ranking, and one selection."""

    summary: str
    problem_statement: str
    candidate_backlog: dict[str, BacklogCandidate] = Field(default_factory=dict)
    preliminary_ranking: list[CandidateRankingEntry] = Field(default_factory=list)
    top_two_comparison: CandidatePairwiseComparison | None = None
    selected_candidate_id: str = ""
    deferred_candidates: dict[str, str] = Field(default_factory=dict)
    benefit: int = Field(ge=1, le=5)
    risk: int = Field(ge=1, le=5)
    effort: int = Field(ge=1, le=5)
    confidence: float = Field(ge=0, le=1)
    decision: Literal["proceed", "abstain", "needs_human"]
    decision_reason: str


class OrchestratorArtifacts(BaseModel):
    """Auditable artifacts from the staged Orchestrator."""

    workflow_diagnosis: WorkflowDiagnosisBoard | None = None
    case_analysis: CaseAnalysisBoard | None = None
    diagnosis: DiagnosisBoard
    selection: SelectionDecision


class SelectedChangeContract(BaseModel):
    """The one frozen execution contract selected for this Loop."""

    contract_id: str
    backlog_item_id: str
    backlog_revision: int = Field(default=1, ge=1)
    objective: str
    rationale: str = ""
    diagnosis: CandidateDiagnosis
    intervention: CandidateIntervention
    inputs: list[ContractClause] = Field(default_factory=list)
    # Unlike a generic requirement, an expected output must explain both why it
    # matters and which observation would support it. This prevents vague nouns
    # such as "correct output" from silently becoming acceptance evidence.
    expected_outputs: list[ScenarioOutcomeCondition] = Field(default_factory=list)
    required_behaviors: list[ContractClause] = Field(default_factory=list)
    implementation_constraints: list[ContractClause] = Field(default_factory=list)
    invariants: list[ContractClause] = Field(default_factory=list)
    prohibited_shortcuts: list[ContractClause] = Field(default_factory=list)
    affected_components: list[str] = Field(default_factory=list)
    allowed_write_paths: list[str] = Field(default_factory=list)
    reviewer_focus: list[str] = Field(default_factory=list)
    required_safety_properties: list[Literal["path_confinement"]] = Field(
        default_factory=list
    )
    acceptance_criteria: list[AcceptanceCriterion] = Field(default_factory=list)
    delivery_run: list[str] = Field(default_factory=list)
    delivery_scenarios: list[DeliveryScenario] = Field(default_factory=list)
    delivery_checklist: list[str] = Field(default_factory=list)
    rollback_plan: str = ""

    def as_task(self) -> ImprovementTask:
        """Compatibility view for the existing serial Writer/Reviewer executor."""

        return ImprovementTask(
            id=self.contract_id,
            candidate=self.backlog_item_id,
            description=self.objective,
            rationale=self.rationale,
            capability_change=self.intervention.expected_capability_delta,
            required_behaviors=[
                *self.inputs,
                *[
                    ContractClause(id=item.id, description=item.description)
                    for item in self.expected_outputs
                ],
                *self.required_behaviors,
            ],
            implementation_constraints=self.implementation_constraints,
            invariants=self.invariants,
            prohibited_shortcuts=self.prohibited_shortcuts,
            affected_components=self.affected_components,
            reviewer_focus=self.reviewer_focus,
            required_safety_properties=self.required_safety_properties,
            dependencies=[],
            acceptance_criteria_ids=[
                criterion.id for criterion in self.acceptance_criteria
            ],
        )

    def as_writer_contract(self) -> WriterTaskContract:
        """Compile the dense audit contract into the shared execution brief."""

        constraints = [
            *self.implementation_constraints,
            *self.invariants,
        ][:4]
        checks = sorted(
            self.acceptance_criteria,
            key=lambda item: (
                not bool(item.verified_safety_properties),
                not item.required,
            ),
        )[:3]
        return WriterTaskContract(
            contract_id=self.contract_id,
            objective=self.objective,
            capability_delta=self.intervention.expected_capability_delta,
            implementation_direction=self.intervention.mechanism,
            requirements=self.required_behaviors[:5],
            constraints=constraints,
            non_goals=self.prohibited_shortcuts[:3],
            suggested_components=self.affected_components[:6],
            required_safety_properties=self.required_safety_properties,
            acceptance_checks=[
                WriterAcceptanceCheck(
                    id=item.id,
                    description=item.description,
                    verification=item.verification,
                )
                for item in checks
            ],
        )


class ContractExpansion(BaseModel):
    """Change-contract artifact; Delivery Design is attached in a later stage."""

    proposal_guardrails: list[ContractClause] = Field(default_factory=list)
    selected_change_contract: SelectedChangeContract
    evidence: list[Evidence] = Field(default_factory=list)
    goals: list[str] = Field(default_factory=list)
    non_goals: list[str] = Field(default_factory=list)
    affected_components: list[str] = Field(default_factory=list)
    dependencies: list[str] = Field(default_factory=list)
    alternatives_considered: list[str] = Field(default_factory=list)


class ScenarioWorkspaceRequirement(BaseModel):
    """One abstract role the disposable coding workspace must materialize."""

    id: str
    role: str
    required_initial_state: str
    purpose: str


class ScenarioComparison(BaseModel):
    """The causal contrast the frozen case is expected to expose."""

    baseline_prediction: str
    candidate_prediction: str
    observable_difference: str
    confounders: list[str] = Field(default_factory=list)


class ScenarioEvidenceRequirement(BaseModel):
    """A semantic claim the execution design must bind to concrete evidence."""

    id: str
    claim: str
    subject: Literal[
        "target_agent_action",
        "task_artifact",
        "environment_result",
    ]
    related_condition_ids: list[str] = Field(default_factory=list)

    @model_validator(mode="before")
    @classmethod
    def migrate_related_outcomes(cls, value):
        """Accept the narrower field name found in earlier run artifacts."""

        if not isinstance(value, dict) or "related_condition_ids" in value:
            return value
        migrated = dict(value)
        migrated["related_condition_ids"] = migrated.pop(
            "related_outcome_ids",
            [],
        )
        return migrated


class DeliveryCaseDefinition(BaseModel):
    """What representative coding case would distinguish the selected capability."""

    contract_id: str
    case_id: str
    capability_under_test: str
    task_contract: ScenarioTaskContract
    workspace_requirements: list[ScenarioWorkspaceRequirement] = Field(min_length=1)
    comparison: ScenarioComparison
    evidence_requirements: list[ScenarioEvidenceRequirement] = Field(min_length=1)


class ScenarioObservationBinding(BaseModel):
    """Bind one frozen evidence claim to runtime components and event sources."""

    evidence_requirement_id: str
    component: str
    evidence_sources: list[
        Literal[
            "agent_input",
            "agent_output",
            "tool_call",
            "tool_result",
            "artifact",
            "final_output",
            "log",
        ]
    ] = Field(min_length=1)


class ScenarioExecutionDesign(BaseModel):
    """Concrete launch and workspace materialization for one frozen case."""

    command: list[str] = Field(min_length=1)
    workspace_seed_files: dict[str, str] = Field(default_factory=dict)
    environment_requirements: list[str] = Field(default_factory=list)
    observation_bindings: list[ScenarioObservationBinding] = Field(default_factory=list)
    budgets: ScenarioBudgets = Field(default_factory=ScenarioBudgets)
    executable_conditions: list[ExecutableCondition] = Field(
        default_factory=list,
        max_length=8,
    )


class DeliveryExecutionDesign(BaseModel):
    """How to execute an already-frozen Delivery Case Definition."""

    contract_id: str
    case_id: str
    acceptance_criteria: list[AcceptanceCriterion] = Field(default_factory=list)
    delivery_run: list[str] = Field(default_factory=list)
    scenario_execution: ScenarioExecutionDesign | None = None
    delivery_checklist: list[str] = Field(default_factory=list)
    rollback_plan: str = ""


class ImprovementBatchBudget(BaseModel):
    """Compatibility metadata for the one-Candidate/one-Task Loop budget."""

    max_candidates: int = Field(default=1, ge=1, le=3)
    max_tasks: int = Field(default=1, ge=1, le=6)
    max_total_effort: int = Field(default=6, ge=1, le=6)
    selected_total_effort: int = Field(default=0, ge=0, le=6)


class OrchestratorAnalysis(BaseModel):
    """Diagnosis plus selection of one Candidate for the next Loop."""

    findings: list[DiagnosticFinding] = Field(default_factory=list)
    candidates: list[InterventionCandidate] = Field(default_factory=list)
    selected_candidates: list[str] = Field(default_factory=list)
    batch_budget: ImprovementBatchBudget = Field(default_factory=ImprovementBatchBudget)
    packing_reason: str = ""
    compatibility_notes: list[str] = Field(default_factory=list)
    selection_reason: str = ""
    causal_mechanism: str = ""
    expected_capability_delta: str = ""

    @model_validator(mode="before")
    @classmethod
    def migrate_singular_selection(cls, value):
        """Read older proposal JSON that used ``selected_candidate``."""
        if isinstance(value, dict):
            data = dict(value)
            if not data.get("selected_candidates") and data.get("selected_candidate"):
                data["selected_candidates"] = [str(data["selected_candidate"])]
            return data
        return value

    @property
    def selected_candidate(self) -> str:
        """Compatibility view for older callers; new code uses the plural field."""
        return self.selected_candidates[0] if self.selected_candidates else ""


# --- the central artifact -------------------------------------------------------


class ImprovementProposal(BaseModel):
    # an RFC-style, evidence-grounded change proposal (design doc section 6.1).
    summary: str
    problem_statement: str
    # Whole-picture boundaries. Implementations may deviate from suggested paths,
    # but Writer/Reviewer/Deliverer must not violate these clauses.
    proposal_guardrails: list[ContractClause] = Field(default_factory=list)
    # New decision interface. Backlog items are decision-level hypotheses; only the
    # selected item is expanded into an execution-level contract.
    candidate_backlog: dict[str, BacklogCandidate] = Field(default_factory=dict)
    # LLM-authored decision artifacts. The framework records their structure but
    # does not calculate a score or override the model's qualitative judgment.
    preliminary_ranking: list[CandidateRankingEntry] = Field(default_factory=list)
    top_two_comparison: CandidatePairwiseComparison | None = None
    selected_candidate_id: str = ""
    selected_change_contract: SelectedChangeContract | None = None
    # Added by the Orchestrator coordinator after contract expansion. The LLM
    # that expands the contract does not need to reproduce these artifacts.
    orchestrator_artifacts: OrchestratorArtifacts | None = None
    # Legacy analysis/task fields remain readable while stored runs migrate.
    analysis: OrchestratorAnalysis = Field(default_factory=OrchestratorAnalysis)
    evidence: list[Evidence] = Field(default_factory=list)
    goals: list[str] = Field(default_factory=list)
    non_goals: list[str] = Field(default_factory=list)
    affected_components: list[str] = Field(default_factory=list)
    # Explicit repo-relative file paths, directory prefixes ending in "/", or
    # glob patterns the Writer is authorized to modify.
    allowed_write_paths: list[str] = Field(default_factory=list)
    dependencies: list[str] = Field(default_factory=list)
    tasks: list[ImprovementTask] = Field(default_factory=list)
    # decision inputs (1-5 scores from the LLM; confidence in [0,1]).
    benefit: int
    risk: int
    effort: int
    confidence: float
    # the LLM's proposed decision; the deterministic policy gate has final say.
    decision: Literal["proceed", "abstain", "needs_human"]
    decision_reason: str
    acceptance_criteria: list[AcceptanceCriterion] = Field(default_factory=list)
    # System-level integration/smoke commands for delivering the changed agent package.
    # Generated-code capability tasks live in the separate post-run eval harness.
    delivery_run: list[str] = Field(default_factory=list)
    # Frozen, capability-specific end-to-end runs. The Deliverer chooses when to invoke
    # them; the execution tool creates an isolated fixture and substitutes only the
    # placeholders explicitly present in the argv command.
    delivery_scenarios: list[DeliveryScenario] = Field(default_factory=list)
    # High-level system requirements the Deliverer checks against the whole-loop diff.
    # Runtime facts are gathered by Deliverer tools; universal failures remain hard gates.
    delivery_checklist: list[str] = Field(default_factory=list)
    evaluation_plan: EvaluationPlan | None = None
    rollback_plan: str = ""
    alternatives_considered: list[str] = Field(default_factory=list)

    def execution_contract(self) -> SelectedChangeContract | None:
        """Return the canonical contract, synthesizing old Proposal records lazily."""

        if self.selected_change_contract is not None:
            return self.selected_change_contract
        if not self.tasks:
            return None
        task = self.tasks[0]
        selected_name = (
            self.analysis.selected_candidate or task.candidate or task.id
        )
        candidate = next(
            (
                item
                for item in self.analysis.candidates
                if item.name == selected_name
            ),
            None,
        )
        finding = self.analysis.findings[0] if self.analysis.findings else None
        capability_gap = (
            candidate.capability_gap
            if candidate and candidate.capability_gap
            else finding.capability_gap
            if finding
            else task.capability_change or task.description
        )
        diagnosis = CandidateDiagnosis(
            symptom=finding.symptom if finding else "",
            root_cause=finding.root_cause if finding else task.rationale,
            capability_gap=capability_gap,
            evidence_refs=(
                candidate.evidence_refs
                if candidate and candidate.evidence_refs
                else finding.evidence_refs
                if finding
                else []
            ),
            uncertainty=finding.uncertainty if finding else "",
        )
        intervention = CandidateIntervention(
            level=candidate.level if candidate else "workflow",
            mechanism=(
                self.analysis.causal_mechanism
                or candidate.mechanism
                if candidate
                else self.analysis.causal_mechanism or task.rationale or task.description
            ),
            expected_capability_delta=(
                candidate.expected_capability_delta
                if candidate
                else self.analysis.expected_capability_delta
                or task.capability_change
                or task.description
            ),
        )
        return SelectedChangeContract(
            contract_id=task.id,
            backlog_item_id=selected_name,
            objective=task.description,
            rationale=task.rationale,
            diagnosis=diagnosis,
            intervention=intervention,
            required_behaviors=task.required_behaviors,
            implementation_constraints=task.implementation_constraints,
            invariants=task.invariants,
            prohibited_shortcuts=task.prohibited_shortcuts,
            affected_components=task.affected_components,
            allowed_write_paths=self.allowed_write_paths,
            reviewer_focus=task.reviewer_focus,
            required_safety_properties=task.required_safety_properties,
            acceptance_criteria=[
                criterion
                for criterion in self.acceptance_criteria
                if criterion.id in task.acceptance_criteria_ids
            ],
            delivery_run=self.delivery_run,
            delivery_scenarios=self.delivery_scenarios,
            delivery_checklist=self.delivery_checklist,
            rollback_plan=self.rollback_plan,
        )

    def execution_tasks(self) -> list[ImprovementTask]:
        if self.selected_change_contract is not None:
            task = self.selected_change_contract.as_task()
            # Proposal guardrails are projected into the shared Writer/Reviewer
            # invariant view. They remain whole-picture boundaries rather than
            # implementation prescriptions.
            return [
                task.model_copy(
                    update={
                        "invariants": [
                            *self.proposal_guardrails,
                            *task.invariants,
                        ]
                    }
                )
            ]
        return self.tasks

    def contract_acceptance_criteria(self) -> list[AcceptanceCriterion]:
        if self.selected_change_contract is not None:
            return self.selected_change_contract.acceptance_criteria
        return self.acceptance_criteria

    def contract_delivery_run(self) -> list[str]:
        if self.selected_change_contract is not None:
            return self.selected_change_contract.delivery_run
        return self.delivery_run

    def contract_delivery_scenarios(self) -> list[DeliveryScenario]:
        if self.selected_change_contract is not None:
            return self.selected_change_contract.delivery_scenarios
        return self.delivery_scenarios

    def contract_allowed_write_paths(self) -> list[str]:
        if self.selected_change_contract is not None:
            return self.selected_change_contract.allowed_write_paths
        return self.allowed_write_paths


class FrozenProposal(BaseModel):
    # an approved proposal, made immutable + hashed so intent can't drift
    # (design doc section 6.2). A substantial change requires a new version.
    proposal_id: str
    proposal_version: int
    proposal_hash: str
    approved_by: str
    approved_at: str
    target_commit: str
    baseline_run_id: str
    proposal: ImprovementProposal
